REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\qrgp\qrgp.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\qrgp\arm\gccmain.o" -c "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\qrgp\include" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\include\component" -I "D:\MyGitHub\qrgp\ResID" -I "D:\MyGitHub\qrgp\src\app\widget" -I "D:\MyGitHub\qrgp\src\app\launcher" -I "D:\MyGitHub\qrgp\src\app\wallpaper" -I "D:\MyGitHub\qrgp\src\app\screen_lock" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\include\component" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\src\framework" -I "D:\MyGitHub\qrgp\src\framework\ui_core\base" -I "D:\MyGitHub\qrgp\src\framework\ui_core\mvc" -I "D:\MyGitHub\qrgp\src\framework\ui_core\pme" -I "D:\MyGitHub\qrgp\src\framework\mmi_core" -I "D:\MyGitHub\qrgp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\qrgp\src\component" -I "D:\MyGitHub\qrgp\src\ui_engine\framework\xml" -I "D:\MyGitHub\qrgp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\qrgp\arm\qrcode_encoder.o" -c "d:\MyGitHub\qrgp\qrcode_encoder.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\qrgp\include" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\include\component" -I "D:\MyGitHub\qrgp\ResID" -I "D:\MyGitHub\qrgp\src\app\widget" -I "D:\MyGitHub\qrgp\src\app\launcher" -I "D:\MyGitHub\qrgp\src\app\wallpaper" -I "D:\MyGitHub\qrgp\src\app\screen_lock" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\include\component" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\src\framework" -I "D:\MyGitHub\qrgp\src\framework\ui_core\base" -I "D:\MyGitHub\qrgp\src\framework\ui_core\mvc" -I "D:\MyGitHub\qrgp\src\framework\ui_core\pme" -I "D:\MyGitHub\qrgp\src\framework\mmi_core" -I "D:\MyGitHub\qrgp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\qrgp\src\component" -I "D:\MyGitHub\qrgp\src\ui_engine\framework\xml" -I "D:\MyGitHub\qrgp"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\qrgp\arm\qrgp.o" -c "d:\MyGitHub\qrgp\qrgp.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\MyGitHub\qrgp\include" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\include\component" -I "D:\MyGitHub\qrgp\ResID" -I "D:\MyGitHub\qrgp\src\app\widget" -I "D:\MyGitHub\qrgp\src\app\launcher" -I "D:\MyGitHub\qrgp\src\app\wallpaper" -I "D:\MyGitHub\qrgp\src\app\screen_lock" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\include\component" -I "D:\MyGitHub\qrgp\include\service" -I "D:\MyGitHub\qrgp\src\framework" -I "D:\MyGitHub\qrgp\src\framework\ui_core\base" -I "D:\MyGitHub\qrgp\src\framework\ui_core\mvc" -I "D:\MyGitHub\qrgp\src\framework\ui_core\pme" -I "D:\MyGitHub\qrgp\src\framework\mmi_core" -I "D:\MyGitHub\qrgp\src\ui_engine\vrt\interface" -I "D:\MyGitHub\qrgp\src\component" -I "D:\MyGitHub\qrgp\src\ui_engine\framework\xml" -I "D:\MyGitHub\qrgp"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\qrgp\qrgp.axf"  "D:\MyGitHub\qrgp\arm\gccmain.o"  "D:\MyGitHub\qrgp\arm\qrcode_encoder.o"  "D:\MyGitHub\qrgp\arm\qrgp.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc_t\percommon.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc_t\perfile.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc_t\persysstorage.a" -l:"C:\Program Files\MRE SDK V3.0.00\lib\MRE30\armgcc_t\persysfile.a"
REM Pack resource to app 
"C:\Program Files\MRE SDK V3.0.00\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\qrgp\qrgp.pkd" -e AXF "D:\MyGitHub\qrgp\qrgp.vcproj" "D:\MyGitHub\qrgp\qrgp.axf"
REM Add tag infromation 
"C:\Program Files\MRE SDK V3.0.00\tools\PackDigist.exe" "D:\MyGitHub\qrgp\qrgp.vcproj" "qrgp" "0.1.0" "RDZDX" "0" "NotSupportBg" "Not Support rotate" "qrgp" "qrgp" "qrgp" "9246012102087182" "content" " File SysStorage SysFile" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\qrgp\arm D:\MyGitHub\qrgp\build.log

